import localFont from "next/font/local";
import "./styles/globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="flex flex-col justify-between w-full min-h-screen bg-background bg-cover bg-no-repeat">
        <Header />
        <main className="flex-grow relative z-0">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
