import localFont from "next/font/local";
import "./styles/globals.css";
import Header from "./components/header";
import Footer from "./components/footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <Header />
        { children }
        <Footer />
      </body>
    </html>
  );
}
